name: Publish
on:
  push:
    # tags:
    #   - 'v*'
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      - name: Cache version
        id: cache-version
        uses: actions/cache@v3
        with:
          path: package.json
          key: ${{ runner.os }}-prod-${{ steps.extract_version.outputs.version }}
      - name: Check version exists
        if: steps.cache-version.outputs.cache-hit == 'true'
        run: exit 1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}